[package]
name = "screeps-starter-rust"
version = "0.0.0"
authors = []
edition = "2018"

[dependencies]
stdweb = "0.4"
log = "0.4"
fern = "0.6"
screeps-game-api = "0.8"
rand = { version = "0.7", features = ["small_rng"] }

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
